import assert from "node:assert/strict";

import {
  cloudOrchestratorQuoteDigest,
  cloudOrchestratorQuoteDocumentForGolden,
} from "../scripts/connection-stack-v2/src/quote-contract.mjs";
import {
  canonicalDeterministicCBOR,
} from "../scripts/connection-stack-v2/src/approval-proof.mjs";

const quote = {
  schema: "dirextalk.aws.quote/v1",
  quote_id: `quote-${"b".repeat(32)}`,
  connection_id: "connection-v2-0001",
  command_id: "command-v2-quote-001",
  request_sha256: "b".repeat(64),
  quote_request_id: "quote-request-v2-001",
  plan_digest: `sha256:${"c".repeat(64)}`,
  region: "ap-south-1",
  currency: "USD",
  quoted_at: "2026-07-14T07:00:00.000Z",
  valid_until: "2026-07-14T07:15:00.000Z",
  // The public quote preserves signed request order. The private Go QuoteV1
  // digest must instead sort by tier/candidate identity.
  candidates: [
    {
      candidate_id: "candidate-performance-01",
      tier: "performance",
      instance_type: "m7i.2xlarge",
      purchase_option: "on_demand",
      estimated_disk_gib: 120,
      architecture: "amd64",
      vcpu: 8,
      memory_mib: 32768,
      gpu_count: 0,
      gpu_memory_mib: 0,
      hourly_minor: 4032,
      thirty_day_minor: 2903040,
      startup_upper_minor: 0,
      availability_zones: ["ap-south-1a", "ap-south-1b"],
    },
    {
      candidate_id: "candidate-economy-0001",
      tier: "economy",
      instance_type: "m7i.large",
      purchase_option: "on_demand",
      estimated_disk_gib: 40,
      architecture: "amd64",
      vcpu: 2,
      memory_mib: 8192,
      gpu_count: 0,
      gpu_memory_mib: 0,
      hourly_minor: 1008,
      thirty_day_minor: 725760,
      startup_upper_minor: 0,
      availability_zones: ["ap-south-1a", "ap-south-1b"],
    },
  ],
  included_items: ["ec2_linux_ondemand"],
  unincluded_items: ["cloudwatch_logs", "data_transfer", "ebs_gp3", "public_ipv4", "snapshots", "taxes"],
};

const request = {
  connection_id: quote.connection_id,
  command_id: quote.command_id,
  request_sha256: quote.request_sha256,
  quote_request: {
    quote_request_id: quote.quote_request_id,
    plan_digest: quote.plan_digest,
    region: quote.region,
    candidates: quote.candidates.map(({ candidate_id, tier, instance_type, purchase_option, estimated_disk_gib }) => ({
      candidate_id,
      tier,
      instance_type,
      purchase_option,
      estimated_disk_gib,
    })),
  },
  issued_at: quote.quoted_at,
  expires_at: quote.quoted_at,
};

const document = cloudOrchestratorQuoteDocumentForGolden(quote, request);
assert.deepEqual(document.candidates.map(({ tier }) => tier), ["economy", "performance"]);
assert.equal(document.quoted_at, "2026-07-14T07:00:00Z", "Go time.Time omits a zero fractional second before canonical CBOR");
assert.equal(document.valid_until, "2026-07-14T07:15:00Z");
assert.deepEqual(document.candidates[0].availability_zones, ["ap-south-1a", "ap-south-1b"]);
assert.deepEqual(document.unincluded_items, ["cloudwatch_logs", "data_transfer", "ebs_gp3", "public_ipv4", "snapshots", "taxes"]);

// Generated by cloudorchestrator.QuoteV1.CanonicalQuoteCBOR/Digest in the Go
// server. It locks the Stack's internal-only quote digest to the same
// deterministic-CBOR contract used by PlanV1 and ApprovalV1.
const wantCBORBase64 = "qmZyZWdpb25qYXAtc291dGgtMWhjdXJyZW5jeWNVU0RocXVvdGVfaWR4JnF1b3RlLWJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiaXF1b3RlZF9hdHQyMDI2LTA3LTE0VDA3OjAwOjAwWmpjYW5kaWRhdGVzgq5kdGllcmdlY29ub215ZHZjcHUCaWdwdV9jb3VudABqbWVtb3J5X21pYhkgAGxhcmNoaXRlY3R1cmVlYW1kNjRsY2FuZGlkYXRlX2lkdmNhbmRpZGF0ZS1lY29ub215LTAwMDFsaG91cmx5X21pbm9yGQPwbWluc3RhbmNlX3R5cGVpbTdpLmxhcmdlbmdwdV9tZW1vcnlfbWliAG9wdXJjaGFzZV9vcHRpb25pb25fZGVtYW5kcHRoaXJ0eV9kYXlfbWlub3IaAAsTAHJhdmFpbGFiaWxpdHlfem9uZXOCa2FwLXNvdXRoLTFha2FwLXNvdXRoLTFicmVzdGltYXRlZF9kaXNrX2dpYhgoc3N0YXJ0dXBfdXBwZXJfbWlub3IArmR0aWVya3BlcmZvcm1hbmNlZHZjcHUIaWdwdV9jb3VudABqbWVtb3J5X21pYhmAAGxhcmNoaXRlY3R1cmVlYW1kNjRsY2FuZGlkYXRlX2lkeBhjYW5kaWRhdGUtcGVyZm9ybWFuY2UtMDFsaG91cmx5X21pbm9yGQ/AbWluc3RhbmNlX3R5cGVrbTdpLjJ4bGFyZ2VuZ3B1X21lbW9yeV9taWIAb3B1cmNoYXNlX29wdGlvbmlvbl9kZW1hbmRwdGhpcnR5X2RheV9taW5vchoALEwAcmF2YWlsYWJpbGl0eV96b25lc4JrYXAtc291dGgtMWFrYXAtc291dGgtMWJyZXN0aW1hdGVkX2Rpc2tfZ2liGHhzc3RhcnR1cF91cHBlcl9taW5vcgBrdmFsaWRfdW50aWx0MjAyNi0wNy0xNFQwNzoxNTowMFpuaW5jbHVkZWRfaXRlbXOBcmVjMl9saW51eF9vbmRlbWFuZG5zY2hlbWFfdmVyc2lvbnVjbG91ZC1vcmNoZXN0cmF0b3IvdjFwdW5pbmNsdWRlZF9pdGVtc4ZvY2xvdWR3YXRjaF9sb2dzbWRhdGFfdHJhbnNmZXJnZWJzX2dwM2twdWJsaWNfaXB2NGlzbmFwc2hvdHNldGF4ZXNzY2xvdWRfY29ubmVjdGlvbl9pZHJjb25uZWN0aW9uLXYyLTAwMDE";
const wantDigest = "sha256:8197814f61c57622244b753dcaea88fdd6bab0c1e5cdf044caf396397151533f";
assert.equal(canonicalDeterministicCBOR(document).toString("base64").replace(/=+$/, ""), wantCBORBase64);
assert.equal(cloudOrchestratorQuoteDigest(quote, request), wantDigest);

console.log("connection stack v2 private quote digest cross-language golden ok");
